[log]
output = "/var/log/revad/revad-shareproviders.log"
level = "info"


[shared]
gatewaysvc = "localhost:9142"
jwt_secret = "your_value_here"
skip_user_groups_in_token = true
db_username = "your_value_here"
db_password = "your_value_here"
db_host = "your_value_here"
db_port = 5504
db_name = "test"



[grpc]
address = "0.0.0.0:9144"

[grpc.services.usershareprovider]
driver = "sql"
allowed_paths_for_shares = ["^/eos/user/[a-z]/[0-9a-z\\-]+/.+", "^/eos/project/[a-z]/[0-9a-z\\-]+/.+", "^/eosdev/project/[a-z]/[0-9a-z\\-]+/.+", "^/winspaces/.+"]

[grpc.services.usershareprovider.drivers.sql]
password_hash_cost = 11
enable_expired_shares_cleanup = false
janitor_run_interval = 60


[grpc.services.publicshareprovider]
driver = "sql"
allowed_paths_for_shares = ["^/eos/user/[a-z]/[0-9a-z\\-]+/.+", "^/eos/project/[a-z]/[0-9a-z\\-]+/.+", "^/eosdev/project/[a-z]/[0-9a-z\\-]+/.+", "^/winspaces/.+"]

[grpc.services.publicshareprovider.drivers.sql]
password_hash_cost = 11

[grpc.services.ocmincoming]
driver = "sql"

[grpc.services.ocmincoming.drivers.sql]


[grpc.services.ocmshareprovider]
driver = "sql"
embedded_driver = "webdav"
webdav_prefix = "https://host.example.org/remote.php/dav/files"
provider_domain = "host.example.org"
webdav_endpoint = "https://host.example.org"
webapp_endpoint = "https://host.example.org/external/sciencemesh"

[grpc.services.ocmshareprovider.drivers.sql]

[grpc.services.ocmshareprovider.embedded_drivers.webdav]
webdav_url = "https://host.example.org/webdav"

[grpc.services.ocminvitemanager]
driver = "sql"
provider_domain = "host.example.org"

[grpc.services.ocminvitemanager.drivers.sql]


[grpc.services.ocmproviderauthorizer]
driver = "open"

[http.services.pprof]

