[log]
output = "/var/log/revad/revad-codimd.log"
mode = "json"

[shared]
gatewaysvc = "localhost:9142"
jwt_secret = "your_secret"
skip_user_groups_in_token = true

[grpc]
address = "0.0.0.0:18501"

[grpc.services.appprovider]
driver = "wopi"
mime_types = ["text/markdown", "application/compressed-markdown", "text/plain", "text/html", "text/php", "text/javascript"]
custom_mime_types_json = "/etc/revad/custom-mimetypes.json"
app_provider_url = "localhost:18501"

[grpc.services.appprovider.drivers.wopi]
iop_secret = "your_secret"
wopi_url = "https://wopi.cernbox.cern.ch:8443"
folder_base_url = "https://cernbox.cern.ch"
app_name = "CodiMD"
app_url = "https://cernbox-codimd.web.cern.ch"
app_int_url = "https://cernbox-codimd.web.cern.ch"
app_icon_uri = "https://cernbox.cern.ch/cernbox/theme-cernbox-0.2.0/assets/codimd-line.svg"
insecure_connections = true

[tracing]

