[log]
output = "/var/log/revad/revad-eosexperiment.log"
mode = "json"

[shared]
gatewaysvc = "localhost:9142"
jwt_secret = "your_secret"
skip_user_groups_in_token = true

[grpc]
address = "0.0.0.0:22000"

[grpc.interceptors.noshare]
[grpc.interceptors.notrashbin]
[grpc.interceptors.noversions]

[grpc.services.storageprovider]
custom_mime_types_json = "/etc/revad/custom-mimetypes.json"
driver = "eoswrapper"
mount_path = "/eos/experiment"
mount_id = "eosexperiment"
data_server_url = "http://localhost:22001/data"

[grpc.services.storageprovider.drivers.eoswrapper]
namespace = "/eos/experiment/"
quota_node = "/eos/experiment/"
master_url = "root://eospublic.cern.ch"
xrdcopy_binary = "/opt/eos/xrootd/bin/xrdcopy"
cache_directory = "/var/tmp/reva"
mount_id_template = "eosexperiment"
use_grpc = false

[http]
address = "0.0.0.0:22001"

[http.services.dataprovider]
driver = "eoswrapper"

[http.services.dataprovider.drivers.eoswrapper]
namespace = "/eos/experiment/"
quota_node = "/eos/experiment/"
xrdcopy_binary = "/opt/eos/xrootd/bin/xrdcopy"
cache_directory = "/var/tmp/reva"
mount_id_template = "eosexperiment"
use_grpc = false
master_url = "root://eospublic.cern.ch"

[tracing]

