[core]
log_file = "stderr"
log_mode = "dev"
max_cpus = "100%"

[log]
level = "debug"
mode = "console"

[http]
network = "tcp"
address = "0.0.0.0:10000"
enabled_services = ["datasvc", "ocdavsvc", "prometheussvc"]
enabled_middlewares = ["cors", "auth"]

[http.middlewares.auth]
gatewaysvc = "0.0.0.0:9999"
credential_strategy = "basic"
token_strategy = "header"
token_writer = "header"
token_manager = "jwt"
skip_methods = ["/owncloud/status.php", "/metrics"]

[http.middlewares.auth.token_managers.jwt]
secret = "Pive-Fumkiu4"

[http.services.datasvc]
driver = "local"
prefix = "data"
temp_folder = "/var/tmp/"

[http.services.datasvc.drivers.local]
root = "/var/tmp/reva/data"

[http.services.ocdavsvc]
prefix = "owncloud"
chunk_folder = "/var/tmp/revad/chunks"
gatewaysvc = "0.0.0.0:9999"

[grpc]
network = "tcp"
address = "0.0.0.0:9999"
enabled_services = ["storageprovidersvc", "authsvc", "storageregistrysvc", "preferencessvc", "usershareprovidersvc", "gatewaysvc"]
enabled_interceptors = ["auth"]

[grpc.interceptors.auth]
token_manager = "jwt"
skip_methods = ["/cs3.gatewayv0alpha.GatewayService/GenerateAccessToken", "/cs3.gatewayv0alpha.GatewayService/WhoAmI", "/cs3.authv0alpha.AuthService/GenerateAccessToken", "/cs3.authv0alpha.AuthService/WhoAmI"]

[grpc.interceptors.auth.token_managers.jwt]
secret = "Pive-Fumkiu4"

[grpc.services.usershareprovidersvc]
driver = "memory"

[grpc.services.storageprovidersvc]
driver = "local"
mount_path = "/"
mount_id = "123e4567-e89b-12d3-a456-426655440000"
data_server_url = "http://0.0.0.0:10000/data"
expose_data_server = true

[grpc.services.storageprovidersvc.available_checksums]
md5   = 100
unset = 1000

[grpc.services.storageprovidersvc.drivers.local]
root = "/var/tmp/reva/data"

[grpc.services.authsvc]
auth_manager = "json"
token_manager = "jwt"
user_manager = "json"

[grpc.services.authsvc.token_managers.jwt]
secret = "Pive-Fumkiu4"

[grpc.services.authsvc.user_managers.json]
users = "./examples/users.demo.json"

[grpc.services.authsvc.auth_managers.json]
users = "./examples/users.demo.json"

[grpc.services.storageregistrysvc]
driver = "static"

[grpc.services.storageregistrysvc.drivers.static.rules]
"/" = "0.0.0.0:9999"
"123e4567-e89b-12d3-a456-426655440000" = "0.0.0.0:9999"


[grpc.services.gatewaysvc]
storageregistrysvc = "0.0.0.0:9999"
authsvc = "0.0.0.0:9999"
publicshareprovidersvc = "0.0.0.0:9999"
usershareprovidersvc = "0.0.0.0:9999"
ocmshareprovidersvc = "0.0.0.0:9999"
appregistrysvc = "0.0.0.0:9999"
preferencessvc = "0.0.0.0:9999"
commit_share_to_storage_grant = true
datagatewaysvc = "http://0.0.0.0:10000/data"
shared_secret_key = "xyz"
